//! Index generator: writes `docs/skills.md` with a categorized table of all skills.

use std::fs;
use std::path::Path;

use crate::error::NlError;
use crate::skills_generator::{SkillCategory, SkillDefinition};

/// Write `docs/skills.md` relative to the output_dir's parent.
///
/// If `output_dir` is `skills/`, the index goes to `docs/skills.md`.
pub fn write_index(output_dir: &Path, skills: &[SkillDefinition]) -> Result<(), NlError> {
    let docs_dir = output_dir.parent().unwrap_or(Path::new(".")).join("docs");
    fs::create_dir_all(&docs_dir)?;

    let mut md = String::new();
    md.push_str("# Skills Index\n\n");
    md.push_str("> Auto-generated by `nlm generate-skills`. Do not edit manually.\n\n");

    // Group by category
    let sections: &[(SkillCategory, &str, &str)] = &[
        (
            SkillCategory::Shared,
            "Shared",
            "Cross-cutting reference for authentication, flags, formats, and errors.",
        ),
        (
            SkillCategory::Service,
            "Services",
            "High-level overviews of the EDM and Surenotify APIs.",
        ),
        (
            SkillCategory::Group,
            "API Groups",
            "Per-module command reference for each API group.",
        ),
        (
            SkillCategory::Helper,
            "Helpers",
            "Multi-step orchestration workflows.",
        ),
        (
            SkillCategory::Utility,
            "Utilities",
            "MCP tool discovery and configuration management.",
        ),
        (
            SkillCategory::Recipe,
            "Recipes",
            "Multi-step task sequences with real commands.",
        ),
        (
            SkillCategory::Persona,
            "Personas",
            "Role-based skill bundles.",
        ),
    ];

    for (cat, heading, description) in sections {
        let matching: Vec<&SkillDefinition> = skills
            .iter()
            .filter(|s| std::mem::discriminant(&s.category) == std::mem::discriminant(cat))
            .collect();
        if matching.is_empty() {
            continue;
        }

        md.push_str(&format!("## {heading}\n\n"));
        md.push_str(&format!("{description}\n\n"));
        md.push_str("| Skill | Description |\n");
        md.push_str("|-------|-------------|\n");
        for skill in &matching {
            md.push_str(&format!(
                "| [{}](../skills/{}/SKILL.md) | {} |\n",
                skill.name, skill.name, skill.description
            ));
        }
        md.push('\n');
    }

    let path = docs_dir.join("skills.md");
    fs::write(&path, &md)?;
    eprintln!("Wrote index: {}", path.display());
    Ok(())
}
